# Config for SimplyNicks

messages:
  nickChangedSuccessfullyMessage: "Your nickname changed as %simplynick_name%!"
  nickChangedByModeratorMessage: "Your nickname changed as %simplynick_name% by a moderator!"
  moderatorNickChangedMessage: "Changed the player's name as %simplynick_name%"
  nickResettedMessage: "Your nickname changed to its original."
  nickResettedMessageByModerator: "Your nickname changed to its original by a moderator."
  moderatorNickResetMessage: "Player's nickname is resetted!"

  error:
    colorPermissionErrorMessage: "Insufficient permission for use that color!"
    permissionErrorMessage: "Insufficient permission for use that command!"
    nickValidationErrorMessage: Your nick needs to be between 3 and 16 characters and not contain special characters.
    playerCannotFoundErrorMessage: "Player must be online for that process."
    nameAlreadyInUseMessage: "The name is already in use!"
    nickFixedByOwnerMessage: "Your fake nickname changed to your original name (%simplynick_name%) because another player have that name!"

countColorCodesAsCharacter: false

# Check here https://minecraft.fandom.com/wiki/Formatting_codes
colors:
  - a
  - 1
  - 2

database:
  url: jdbc:mysql://127.0.0.1:3306/simplynicks?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  username: user123
  password: pass123
  nickTableName: player_nick
