# Config for SimplyNicks

messages:
  nickChangedSuccessfullyMessage: "Your nick changed to [nick]."
  nickChangedByModeratorMessage: "A moderator changed your nick to [nick]."
  moderatorNickChangedMessage: "Changed the player's nick to [nick]."
  nickResetMessage: "Your nick has been reset."
  nickResetMessageByModerator: "A moderator reset your nick."
  moderatorNickResetMessage: "Player's nick has been reset."
  realname: "[nick]'s real username is [realname]."
  displayname: "[realname]'s nick is [nick]"

  error:
    colorPermissionErrorMessage: "Insufficient permission to use that color."
    permissionErrorMessage: "Insufficient permissions."
    nickValidationErrorMessage: "Your nick needs to be between 3 and 16 characters and not contain special characters."
    playerCannotFoundErrorMessage: "Player not found."
    nickAlreadyInUseMessage: "Nick already in use."
    nickFixedByOwnerMessage: "Your nick has been reset due to naming collision."
    nickNotFound: "Player does not have a nick."

# Check here https://minecraft.fandom.com/wiki/Formatting_codes
colors:
  - a
  - 1
  - 2

database:
  url: jdbc:mysql://127.0.0.1:3306/simplynicks?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  username: user123
  password: pass123
  nickTableName: player_nick
