# Config for SimplyNicks

messages:
  nickChangedSuccessfullyMessage: "Your nickname changed as %simplynick_name%!"
  nickChangedByModeratorMessage: "Your nickname changed as %simplynick_name% by a moderator!"
  moderatorNickChangedMessage: "Changed the player's name as %simplynick_name%"
  nickResettedMessage: "Your nickname changed to its original."
  nickResettedMessageByModerator: "Your nickname changed to its original by a moderator."
  moderatorNickResetMessage: "Player's nickname is resetted!"

  error:
    colorPermissionErrorMessage: "Insufficient permission for use that color!"
    permissionErrorMessage: "Insufficient permission for use that command!"
    shortNickErrorMessage: "Your name is so short! Name must be contained 3 character"
    longNickErrorMessage: "Your name is so long! A name can be maximum of 16 character."
    playerCannotFoundErrorMessage: "Player must be online for that process."
    nameAlreadyInUseMessage: "The name is already in use!"
    nickFixedByOwnerMessage: "Your fake nickname changed to your original name (%simplynick_name%) because another player have that name!"


permissions:
  # Player can change own name
  changeOwnName: changename

  # Player can change other player's name
  changeOthersName: changeothersname

  # Player can access to list of defaultColors
  accessColors: accesscolors


countColorCodesAsCharacter: false
# if that config if false player can use all colors who have OP
OPColorPermissionCheck: false

# Check here https://minecraft.fandom.com/wiki/Formatting_codes
# All colors
# Use & instead of ยง
colors: [
  "&a",
  "&1",
  "&2"
]

database:
  url: jdbc:mysql://127.0.0.1:3306/simplynicks?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
  username: user123
  password: pass123
  nickTableName: player_nick
