main: net.simplyvanilla.simplynicks.SimplyNicks
name: SimplyNicks
version: @version@
api-version: 1.19

author: Simply Vanilla
website: https://github.com/SimplyVanilla/SimplyNicks
folia-supported: true

commands:
  nick:
    description: Change your nickname
    usage: |
           /nick NICKNAME - Set your nick.
           /nick reset - Reset your nick.
    permission: simplynicks.nick

  realname:
    description: Shows a player's username by searching their nick.
    usage: 'Usage: /<command> NICKNAME'
    aliases:
      - rname

permissions:
  simplynicks.nick:
    description: allows access to the nick and realname command
    default: true

  simplynicks.colors.default:
    description: whether the player can use default colors in their nick
    default: false

  simplynicks.colors.all:
    description: whether the player can use all colors in their nick
    default: false

  simplynicks.changeothers:
    description: whether the player can change other player nick
    default: op
