main: net.simplyvanilla.simplynicks.SimplyNicks
name: SimplyNicks
version: @version@
api-version: 1.19

author: Simply Vanilla
website: https://github.com/SimplyVanilla/SimplyNicks

commands:
  nick:
    description: Change your nickname
    usage: |
      /nick NICKNAME - Set your nick.
      /nick reset - Reset your nick.
    permission: simplynicks.changenick

  realname:
    description: Shows a player's username by searching their nick.
    usage: 'Usage: /<command> NICKNAME'
    aliases:
      - rname
    permission: simplynicks.showname

  displayname:
    description: Shows a player's nick.
    usage: 'Usage: /<command> USERNAME'
    aliases:
      - dname
    permission: simplynicks.showname

permissions:
  simplynicks.showname:
    description: whether the player can show a player's user or display name
    default: true

  simplynicks.changenick:
    description: whether the player can change their own nick
    default: false

  simplynicks.colors.default:
    description: whether the player can use default colors in their nick
    default: false

  simplynicks.colors.all:
    description: whether the player can use all colors in their nick
    default: false

  simplynicks.changeothers:
    description: whether the player can change other player nick
    default: op
